#!/bin/sh

PKGS=""

# sudo apt-get install linux-headers-generic build-essential git vim pdftk sox terminator minicom

# sudo apt-get install dconf-tools

#sudo apt-get install emacs

# touch ~/.emacs
# echo ';; -*- mode: emacs-lisp; -*-' >> ~/.emacs

# echo "(load \"~/env/elisp/core-utils.el]\")" >> ~/.emacs

# sudo apt-get install devilspie wmctrl
# sudo apt-get install texlive-extra-utils
#sudo apt-get install cscope mplayer

# dpkg -S /bin/ls
#sudo apt-get install openjdk-6-jre-headless

# git config credential.helper store
#!/bin/sh


# mkdir -p ~/.config/terminator
# mkdir -p ~/.config/terminator/plugins
# cp config ~/.config/terminator/config

# gsettings set org.gnome.desktop.default-applications.terminal exec x-terminal-emulator
# gsettings set org.gnome.desktop.default-applications.terminal exec-arg ""

# sudo apt-get install dconf-tools
# dconf dump /org/gnome/desktop/wm/keybindings/ > keybindings-backup.dconf
# dconf load /org/gnome/desktop/wm/keybindings/ < keybindings-backup.dconf



# gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/']"
# You then set the name, command and binding values

# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ name "shutter"
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ command "shutter -s"
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/ binding "Print"

# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ name "shutter"
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/ command "shutter -f"
# gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gn

# sudo apt-get install memlockd
# sudo apt-get install tmux

# enable virtual desktop (workspace)
# gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ hsize 2
# gsettings set org.compiz.core:/org/compiz/profiles/unity/plugins/core/ vsize 2


# sudo add-apt-repository ppa:numix/ppa
# sudo apt-get update
# sudo apt-get install numix-icon-theme-circle numix-gtk-theme

# gsettings set org.gnome.desktop.interface gtk-theme "Numix"
# gsettings set org.gnome.desktop.wm.preferences theme "Numix"
# gsettings set org.gnome.desktop.interface icon-theme "Numix-Circle"
# gsettings set com.canonical.desktop.interface scrollbar-mode normal

# sudo adduser sagar sudo
# sudo usermod -a -G sudo sagar
# sudo cp sudoall /etc/sudoers.d/

# # Lock screen
# gsettings set com.canonical.unity-greeter draw-user-backgrounds 'false'
# gsettings set com.canonical.unity-greeter background '/home/sagar/env/Pictures/52168_Radha-Krishna-ISKCON-Desire-Tree-Devotee-Network_2592x1944.jpg'

# # Wallpaper
# gsettings set org.gnome.desktop.background picture-uri file:///home/sagar/env/Pictures/52080_Sri-Radha-Krishna-Lalita-Vishakha-Wallpaper-001-Size-2400-1800_2400x1800.jpg

gsettings set org.compiz.integrated show-hud "['<Alt><Super>']"
gsettings set org.compiz.integrated show-launcher "['']"
gsettings list-keys org.compiz.integrated

# #---
# gsettings set org.gnome.desktop.wm.preferences mouse-button-modifier '<Super>'

# gsettings set org.gnome.desktop.wm.keybindings activate-window-menu ['"<Super>space"']

# gsettings set org.gnome.desktop.wm.keybindings begin-move ['"<Super>F7"']

# gsettings set org.gnome.desktop.wm.keybindings begin-resize ['"<Super>F8"']

# gsettings set org.gnome.desktop.wm.keybindings close ['"<Super>F4"']

# gsettings set org.gnome.desktop.wm.keybindings toggle-shaded ['"<Super><Alt>s"']

# gsettings set org.gnome.settings-daemon.plugins.media-keys terminal ''
