#!/bin/sh

opened=`wmctrl -l | grep 'emacs-main'`
running=`ps aux | grep 'emacs23 --daemon' | grep -v grep`

if [ "X$opened" == "X" ]; then
    if [ "X$running" == "X" ]; then
	emacs23 --daemon
    fi

    emacsclient.emacs23 -n -c
    emacsclient.emacs23 -n -e '(set-main)'
    /home/sagar/automate-system/current-max
else
    wmctrl -a emacs-main
fi

