#!/bin/sh

opened=`wmctrl -l | grep Terminal`
echo $opened

# wmctrl -k on

if [ "X$opened" == "X" ]; then
    gnome-terminal
    /home/sagar/env/scripts/setterminal
else
    wmctrl -a "Terminal"
fi

