#!/bin/sh

opened=`wmctrl -l | grep 'Coder'`
running=`ps aux | grep 'emacs --daemon' | grep -v grep`

if [ "X$opened" == "X" ]; then
    if [ "X$running" == "X" ]; then
	emacs --daemon
    fi

    emacsclient -n -c
    emacsclient -n -e '(coder)'
    sleep 1
    /home/sagar/env/scripts/setemacs
else
    wmctrl -a Coder
fi

