#!/bin/bash                                                                                       

wnd_focus=$(xdotool getwindowfocus)
wnd_title=$(xprop -id $wnd_focus WM_NAME)
lookfor='"(.*)"'
if [[ "$wnd_title" =~ $lookfor ]]; then
	wnd_title=${BASH_REMATCH[1]}
	echo $wnd_title > ~/window-id
fi

wmctrl -r :ACTIVE: -b toggle,maximized_vert,maximized_horz

wmctrl -r :ACTIVE: -e 0,0,0,800,850
wmctrl -r :ACTIVE: -b add,maximized_vert
