#!/bin/sh

CP="cp"

if [ "X${SOURCE}" == "X" ]; then
    SOURCE="/home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04"
fi
echo ${SOURCE}
DEST="/home/sagar/workspace/dev-kernel/embedded-linux.xml/zFAS"

# QB1: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/quickboot/_out/debug_p2360/images/quickboot1.bin
# QB2: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/quickboot/_out/debug_p2360/images/cpu_stage2.bin
# QB DTB: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/quickboot/quickboot-partner/data_driven/_out/t124-p2360.dtb

# RCM-bootloader: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/quickboot/_out/debug_p2360/images/rcmboot.bin
# RCM_Flashing Bootloader: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/rcmboot.bin

# RCM_Flashing Kernel: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/zImage
# RCM_Flashing DTB: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel//tegra124-p2360.dtb

# Compressed Kernel: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage
# Uncompress Kernel: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image
# DTB File: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb
# Config file: /home/sagar/workspace/branches/k310-embedded.xml/embedded/zFAS-23.10.04/embedded/tools/boards/p2360/nvflash/quickboot_snor_linux_earlyvideo.cfg

# ${CP} ${SOURCE}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage                            ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage
# ${CP} ${SOURCE}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image                             ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image
# ${CP} ${SOURCE}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb            ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb

# ${CP} ${SOURCE}/embedded/tools/scripts/bootburn/../../boards/flashing_kernel/zImage                          ${DEST}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/zImage
# ${CP} ${SOURCE}/embedded/tools/scripts/bootburn/../../boards/flashing_kernel/tegra124-vcm30t124-flashing.dtb ${DEST}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel//tegra124-p2360.dtb

# ${CP} ${SOURCE}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/zImage                    ${DEST}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/zImage
# ${CP} ${SOURCE}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/tegra124-p2360.dtb        ${DEST}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel//tegra124-p2360.dtb

# ${CP} ${SOURCE}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image                             ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image
# ${CP} ${SOURCE}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage                            ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage
# ${CP} ${SOURCE}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb            ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb

${CP} ${SOURCE}/out/embedded-linux-p2360-release/nvidia/kernel/arch/arm/boot/Image                             ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image
${CP} ${SOURCE}/out/embedded-linux-p2360-release/nvidia/kernel/arch/arm/boot/zImage                            ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage
${CP} ${SOURCE}/out/embedded-linux-p2360-release/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb            ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb

mkdir -p ~/images
${CP} ${SOURCE}/out/embedded-linux-p2360-release/nvidia/kernel/arch/arm/boot/Image                             ~/images
${CP} ${SOURCE}/out/embedded-linux-p2360-release/nvidia/kernel/arch/arm/boot/zImage                            ~/images
${CP} ${SOURCE}/out/embedded-linux-p2360-release/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb            ~/images

# ls -l ${DEST}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel/zImage
# ls -l ${DEST}/embedded/tools/scripts/bootburn/../../boards/p2360/flashing_kernel//tegra124-p2360.dtb
# ls -l ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/Image
# ls -l ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/zImage
# ls -l ${DEST}/out/embedded-linux-p2360-debug/nvidia/kernel/arch/arm/boot/dts/tegra124-p2360.dtb
