#!/bin/bash

firstdate=$1;
secondate=$2;

fullyear=$(date -d@$(( ( $(date -ud "$secondate" +'%s') - $(date -ud "$firstdate" +'%s') ) )) +'%Y years %m months %d days %H hours %M minutes %S seconds')
yearsubtraction=$(( $(echo $fullyear | sed -r 's/^([0-9]+).*/\1/') - 1970 ))

if [ $yearsubtraction -le '0' ]; then
  echo $fullyear | sed -r "s/^([0-9]+) years //" 
else
  echo $fullyear | sed -r "s/^([0-9]+) /$(printf %02d $yearsubtraction) /"
fi