#!/bin/bash

ROOT="$1"
FILE="$2"

# echo "ROOT: \"$ROOT\""
# echo "FILE: \"$FILE\""

DIR="$FILE"
while true; do
    DIR=`dirname "$DIR"`

    ls "$DIR/Makefile" 1>/dev/null 2>/dev/null
    if [ "$?" -eq 0 ]; then
        echo "Building Project `basename $DIR`"
        make auto --no-print-directory -C "$DIR"
        exit
    fi

    if [ "$ROOT" == "$DIR" ]; then
        exit
    fi
done
