#!/bin/sh

TMUX="tmux -2"

if [ "X$1" == "X" ]; then
    BRANCH="23.22"
fi

runon()
{
    session_name=Workspace
    window=${session}:$1
    # pane=${window}.0
    ${TMUX} send-keys -t "$window" "$2" Enter
}

${TMUX} new-session -d -s "Workspace" -n "Minicom"

${TMUX} new-window -n "Recovery" -t "Workspace"

${TMUX} new-window -n "rel-23"   -t "Workspace"
${TMUX} new-window -n "zFAS"     -t "Workspace"

${TMUX} new-window -n "Env"      -t "Workspace"
${TMUX} new-window -n "Debug"    -t "Workspace"

${TMUX} select-window -t "Workspace:zFAS"

runon Minicom "sudo minicom -D /dev/ttyUSB0"
runon Recovery "sudo minicom -D /dev/ttyUSB1"

runon rel-23 "cd ~/workspace/branches/k310-embedded.xml/rel-23"
runon rel-23 ". tmake/scripts/envsetup.sh"
runon rel-23 "choose embedded-linux p2360 none release external armv7"

runon zFAS "cd /home/sagar/workspace/branches/k310-embedded.xml/embedded-cust/audi/zfas-1"

runon zFAS ". tmake/scripts/envsetup.sh"
runon zFAS "choose embedded-linux p2360 none release external armv7"

tmux a
