#!/bin/sh

session_name=Workspace
window=${session_name}:Recovery
# pane=${window}.0
# tmux send-keys -t "${window}" 'tegrarecovery' Enter
tmux send-keys -t "${window}" 'tegrareset' Enter

sleep 1
window=${session_name}:zFAS
tmux send-keys -t "${window}" C-z 'flash -R' Enter

# tmux select-pane -t "$pane"
# tmux select-window -t "$window"
# tmux attach-session -t "$session_name"
