#!/bin/sh

res=`wmctrl -d | awk '{print $9}'`

width=`echo $res | awk -F'x' '{print $1}'`
height=`echo $res | awk -F'x' '{print $2}'`

# terminalid=`wmctrl -l | grep 'Terminal' | awk '{print $1}'`
# echo "$terminalid" $width $height

# wmctrl -r "Terminal :: Workspace :: Env" -e 1,0,0,$((${width} - 60)),$((${height} - 50))
# windowtool.py -d 0 "$terminalid"
# wmctrl -r "Terminal" -e 1,24,49,${width},$((${height} + 5))

wmctrl -r Chrome -e 1,25,49,$((${width} - 40)),$((${height} - 15))
chromeid=`wmctrl -l | grep 'Chrome' | awk '{print $1}'`
/home/sagar/env/scripts/windowtool.py -d 0 "$chromeid"
