#!/bin/sh

res=`wmctrl -d | awk '{print $9}'`

width=`echo $res | awk -F'x' '{print $1}'`
height=`echo $res | awk -F'x' '{print $2}'`

# echo $width $height
wmctrl -r emacs-main -e 1,30,49,$((${width} - 60)),$((${height} - 20))

emacsid=`wmctrl -l | grep 'emacs-main' | awk '{print $1}'`
windowtool.py -d 0 "$emacsid"
