#!/bin/bash

# pdftk original/Skandamu10A.pdf original/Skandamu10B.pdf \
#     original/Skandamu10C.pdf cat output original/Skandamu10.pdf
# pdftk original/Skandamu11A.pdf original/Skandamu11B.pdf \
#     cat output original/Skandamu11.pdf

# #### Skanda 10 pages
# lines=`grep . pages/Skandamu10A.txt | wc -l`
# grep . pages/Skandamu10A.txt | head -$((${lines} - 1)) \
#     > pages/Skandamu10.txt
# lines=`grep . pages/Skandamu10B.txt | wc -l`
# grep . pages/Skandamu10B.txt | head -$((${lines} - 1)) \
#     > pages/Skandamu10B.tmp
# while read no
# do
#     echo $(($no + 251)) >> pages/Skandamu10.txt
# done < pages/Skandamu10B.tmp
# lines=`grep . pages/Skandamu10C.txt | wc -l`
# grep . pages/Skandamu10C.txt > pages/Skandamu10C.tmp
# while read no
# do
#     echo $(($no + 487)) >> pages/Skandamu10.txt
# done < pages/Skandamu10C.tmp
# rm -rf pages/Skandamu10B.tmp pages/Skandamu10C.tmp

# #### Skanda 11 pages
# lines=`grep . pages/Skandamu11A.txt | wc -l`
# grep . pages/Skandamu11A.txt | head -$((${lines} - 1)) \
#     > pages/Skandamu11.txt
# lines=`grep . pages/Skandamu10B.txt | wc -l`
# grep . pages/Skandamu11B.txt > pages/Skandamu11B.tmp
# while read no
# do
#     echo $(($no + 196)) >> pages/Skandamu11.txt
# done < pages/Skandamu11B.tmp
# rm -rf pages/Skandamu11B.tmp

### Processing
src_files=`ls original/*.pdf`

src_files=original/Skandamu10.pdf

for src in $src_files
do
    dest=`echo "$src" | cut -d '/' -f 2`
    mkdir -p uncompress
    if [ ! -e uncompress/$dest ]; then
	pdftk "$src" output "uncompress/$dest" uncompress
    fi

    dest=`echo "$src" | cut -d '/' -f 2 | awk -F '.' '{print $1}'`
    rm -rf split/${dest}

    OLD=""
    NEW=""
    verify=""
    val=1

    while read p
    do
	NEW=$p
	is_last=`echo ${NEW} | awk '{print $2}'`
	
	if [ "X$OLD" != "X" ] && [ "X$NEW" != "X" ]; then
	    mkdir -p split/${dest}

	    if [ "X${is_last}" == "X-1" ]; then
		pdftk "uncompress/${dest}.pdf" cat $OLD-$(($NEW - 1)) \
		    output "split/${dest}/${val}.pdf" uncompress
	    else
		pdftk "uncompress/${dest}.pdf" cat $OLD-$NEW output \
		    "split/${dest}/${val}.pdf" uncompress
	    fi

	    val=$(($val + 1))
	fi

	OLD=$NEW

	verify="$verify $OLD"
    done < pages/$dest.txt
    val=$(( $val - 1))

    mkdir -p questions
    touch questions/${dest}.txt
    if [ $val -gt 0 ]; then
	echo ${dest}: $val Chapters created!
	pdftk "uncompress/${dest}.pdf" cat $verify output \
	    "split/${dest}/verify.pdf" uncompress
    fi
done
